import "../styles/globals.css";

import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import localFont from "next/font/local";

const recoletaAlt = localFont({
  src: "../../public/assets/fonts/RecoletaAlt-SemiBold.woff",
  variable: "--font-recoletaAlt-semiBold",
  weight: "600",
});

const mulish = Mulish({
  subsets: ["latin"],
  variable: "--font-mulish",
  weight: ["200", "300", "400", "500", "600", "700", "800", "900", "1000"],
});

export const metadata: Metadata = {
  title: "itw – crm",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${recoletaAlt.variable} ${mulish.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
